# Generated by Django 5.2.7 on 2025-11-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_has_roommate_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePicture',
            field=models.URLField(default=None, max_length=500),
        ),
    ]
