# Generated by Django 5.2.7 on 2025-11-25 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Apartment Listing", max_length=200),
                ),
                ("description", models.TextField()),
                (
                    "location",
                    models.CharField(help_text="e.g., Downtown LA", max_length=200),
                ),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                ("city", models.CharField(default="Los Angeles", max_length=100)),
                ("state", models.CharField(default="CA", max_length=40)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude for map marker",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude for map marker",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "bedrooms",
                    models.CharField(
                        choices=[
                            ("1bed", "1 Bedroom"),
                            ("2bed", "2 Bedrooms"),
                            ("3bed", "3 Bedrooms"),
                            ("4bed", "4+ Bedrooms"),
                        ],
                        default="1bed",
                        max_length=20,
                    ),
                ),
                (
                    "bathrooms",
                    models.CharField(
                        choices=[
                            ("1bath", "1 Bathroom"),
                            ("2bath", "2 Bathrooms"),
                            ("3bath", "3+ Bathrooms"),
                        ],
                        default="1bath",
                        max_length=20,
                    ),
                ),
                ("square_feet", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("private", "Private Room"),
                            ("shared", "Shared Room"),
                            ("entire", "Entire Place"),
                        ],
                        default="private",
                        max_length=50,
                    ),
                ),
                (
                    "amenities",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated: parking,gym,pool,laundry,ac",
                        max_length=500,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        default="https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("available_from", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartment_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Apartment Post",
                "verbose_name_plural": "Apartment Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteApartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the apartment was favorited"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about why user likes this apartment",
                        null=True,
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        help_text="The apartment that was favorited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="apartments.apartmentpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who favorited this apartment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_apartments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite Apartment",
                "verbose_name_plural": "Favorite Apartments",
                "ordering": ["-created_at"],
                "unique_together": {("user", "apartment")},
            },
        ),
    ]
