# Generated by Django 5.2.7 on 2025-11-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0004_alter_roommatepost_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatepost',
            name='numberOfPeopleInterested',
            field=models.IntegerField(default=0),
        ),
    ]
